// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SiaIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type SiaSiaIpStats struct {
	_             structs.HostLayout
	ConsensusUp   uint64
	ConsensusDown uint64
	SiamuxUp      uint64
	SiamuxDown    uint64
	QuicUp        uint64
	QuicDown      uint64
}

// LoadSia returns the embedded CollectionSpec for Sia.
func LoadSia() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SiaBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Sia: %w", err)
	}

	return spec, err
}

// LoadSiaObjects loads Sia and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SiaObjects
//	*SiaPrograms
//	*SiaMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSiaObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSia()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SiaSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SiaSpecs struct {
	SiaProgramSpecs
	SiaMapSpecs
	SiaVariableSpecs
}

// SiaProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SiaProgramSpecs struct {
	TcEgress   *ebpf.ProgramSpec `ebpf:"tc_egress"`
	XdpIngress *ebpf.ProgramSpec `ebpf:"xdp_ingress"`
}

// SiaMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SiaMapSpecs struct {
	Ip4Stats   *ebpf.MapSpec `ebpf:"ip4_stats"`
	Ip6Stats   *ebpf.MapSpec `ebpf:"ip6_stats"`
	PortConfig *ebpf.MapSpec `ebpf:"port_config"`
	TcLastIp4  *ebpf.MapSpec `ebpf:"tc_last_ip4"`
}

// SiaVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SiaVariableSpecs struct {
}

// SiaObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSiaObjects or ebpf.CollectionSpec.LoadAndAssign.
type SiaObjects struct {
	SiaPrograms
	SiaMaps
	SiaVariables
}

func (o *SiaObjects) Close() error {
	return _SiaClose(
		&o.SiaPrograms,
		&o.SiaMaps,
	)
}

// SiaMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSiaObjects or ebpf.CollectionSpec.LoadAndAssign.
type SiaMaps struct {
	Ip4Stats   *ebpf.Map `ebpf:"ip4_stats"`
	Ip6Stats   *ebpf.Map `ebpf:"ip6_stats"`
	PortConfig *ebpf.Map `ebpf:"port_config"`
	TcLastIp4  *ebpf.Map `ebpf:"tc_last_ip4"`
}

func (m *SiaMaps) Close() error {
	return _SiaClose(
		m.Ip4Stats,
		m.Ip6Stats,
		m.PortConfig,
		m.TcLastIp4,
	)
}

// SiaVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSiaObjects or ebpf.CollectionSpec.LoadAndAssign.
type SiaVariables struct {
}

// SiaPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSiaObjects or ebpf.CollectionSpec.LoadAndAssign.
type SiaPrograms struct {
	TcEgress   *ebpf.Program `ebpf:"tc_egress"`
	XdpIngress *ebpf.Program `ebpf:"xdp_ingress"`
}

func (p *SiaPrograms) Close() error {
	return _SiaClose(
		p.TcEgress,
		p.XdpIngress,
	)
}

func _SiaClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sia_bpfel.o
var _SiaBytes []byte
